### ISSUE TITLE
Introduce a "valid-classes" config option to restrict the tracker to some classes only

### ISSUE THREAD

**Issue by smacinnes** [moovel/lab-opendatacam#51] opened 2018-08-29 17:22 UTC
I noticed you guys recently put out a new update. I really liked the addition of ID tags and being able to download the data without stopping tracking, I think that will be very useful, but I've got some questions. 

Firstly, why are you tracking chairs now? Since this isn't shown in the UI, I was very surprised when counterData.csv had tracked my office chair. 
[counterData.csv.txt](https://github.com/moovel/lab-opendatacam/files/2333068/counterData.csv.txt)

Secondly, it kept giving me the same file instead of a new one when I would download without stopping tracking. The UI correctly displayed the new totals but it kept giving me the data from the first set. To get an updated csv file I had to reinitialize the tracker. 

Thirdly, I've noticed frequent double counting that I didn't notice in the last version. See lines 7 and 8 of the file below for example.

Fourthly, it also seems like the "Unique ID Tags" aren't very unique. See lines 3 and 22 of the file below. Plus there was only ever one chair and one person and neither ever left the sight of the camera.

[counterData (10).csv.txt](https://github.com/moovel/lab-opendatacam/files/2333540/counterData.10.csv.txt)

**Comment by tdurand** [comment] 2018-09-03 07:01
1. Yes, we expose all the voc.names
2. Seems a bug, will check this next week
3. The doubles counting can happen depending on how the objects move in the scene, unfortunately the accuracy of YOLO trained with voc weights is not that good, and the bbox resulting can be one side of the line and be another side of the line in the next frame and counted twice... What would help would be a footage of what you are counting to evaluate this better + keep in mind this was only really tested on cars. (But we didn't change anything on the counting logic on this update so the results shouldn't be different from previous version)
4. It is an unique id, what happened there is that the bbox of the "person" line 3 was pretty similar with the one of the chair, and then on the next frames YOLO must have lost track of the person "recycled" the bbox of the person into the one of the chair, the tracking algorithm is set to try at all cost to keep the existing ids "alive" ... This is due to YOLO beeing poor to distinguish Motorbike / bike, Truck / Cars and we found for our use cases that is was better to keep tracking things even if they change "type"... Hope this is clear.. In this case we could had some "allowed" transition, because obviously chair -> person is not possible and YOLO makes better the difference than mobility classes.

Thanks again for your report 👌. Let me know if you need further explanation, not sure if everything is really clear, and I will push some fix for the tracker data export thing next week.

**Comment by tdurand** [comment] 2018-09-03 07:03
Regarding 1. I have a doubt now I though we might have restricted the thing to the 6 classes of mobility.. I will check also if this is not a bug... because it makes sense to avoid tracking chair and stuff so the tracker isn't mislead by other irrelevant objects.

**Comment by tdurand** [comment] 2018-09-11 15:49
Back with more comments on this:

1. I confirmed we currently expose all voc.names to the tracker.. I'm not sure the best way to go here, maybe it would be good to filter out the non-mobility classes before feeding the tracker to avoid having it mixed up by some random things, @b-g some thoughts about it ?

2. I fixed the bug, it should be good now (fixed on master, released as 0.2.1)

**Comment by b-g** [comment] 2018-10-02 08:08
@tdurand Many thanks for looking into it! 

> I confirmed we currently expose all voc.names to the tracker.. I'm not sure the best way to go here, maybe it would be good to filter out the non-mobility classes before feeding the tracker to avoid having it mixed up by some random things, @b-g some thoughts about it ?

I would vote to have an optional setting `valid-classes`. If set, only these classes are used and everything else with a different class is ignored. If not set, every detection is taken into account (like it is currently).

What you think guys?

**Comment by tdurand** [comment] 2018-10-03 10:58
Ok, would be a good way to close this, I guess this config should be set by default to the mobility classes. From what I remember YOLO was confuses by similar things like: scooter / bike or truck / car, but I can not remember that it was mixing things like chair / person ... 

Will do.

**Comment by tdurand** [comment] 2019-01-09 19:03
Done on the latest release is v0.2.2, published here: https://github.com/moovel/lab-opendatacam/releases/tag/v0.2.2.

Documentation for this config option is here: https://github.com/moovel/lab-opendatacam#track-only-specific-classes

**Comment by b-g** [comment] 2019-01-10 06:40
@tdurand Many thanks + great! Tiny detail: Find it not very self explanatory that `"VALID_CLASSES": [""]` basically means all classes or ignore nothing. Or what do you think? Maybe better? `"VALID_CLASSES": ["*"]`

**Comment by tdurand** [comment] 2019-01-10 13:31
Done on v0.2.3 : https://github.com/moovel/lab-opendatacam/releases/tag/v0.2.3 , doc updated.

**Closed by tdurand** 2019-01-10 13:31 UTC
