### ISSUE TITLE
Issues while running opendatacam

### ISSUE THREAD

**Issue by syedmustafa54** [moovel/lab-opendatacam#58] opened 2019-01-10 08:28 UTC
when i run``` yarn run dev``` or``` npm run dev``` 
```bintex@bintix:/media/bintex/ubuntu/yolo/test/lab-opendatacam$ yarn run dev
yarn run v1.12.3
warning package.json: No license field
$ node server.js
Please specify the path to the raw detections file
Process YOLO initialized
Process WebcamStream initialized


 DONE  Compiled successfully in 833ms                            1:56:43 PM

> Ready on http://localhost:8080
> Ready on http://192.168.1.191:8080
Client pings, but there's no entry for page: /
> Building page: /


 DONE  Compiled successfully in 1068ms                           1:56:50 PM



 WAIT  Compiling...                                              1:56:51 PM



 DONE  Compiled successfully in 74ms                             1:56:51 PM

Thu Jan 10 2019 13:56:55 GMT+0530 (India Standard Time) Connection accepted.
WebSocket Client Connected
Filtered out 1 detections that weren't valid classes
RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 4294967295. Received -55731498
    at checkInt (internal/buffer.js:35:11)
    at writeU_Int32BE (internal/buffer.js:623:3)
    at Buffer.writeUInt32BE (internal/buffer.js:636:10)
    at WebSocketFrame.toBuffer (/media/bintex/ubuntu/yolo/test/lab-opendatacam/node_modules/websocket/lib/WebSocketFrame.js:257:24)
    at WebSocketConnection.sendFrame (/media/bintex/ubuntu/yolo/test/lab-opendatacam/node_modules/websocket/lib/WebSocketConnection.js:857:43)
    at WebSocketConnection.fragmentAndSend (/media/bintex/ubuntu/yolo/test/lab-opendatacam/node_modules/websocket/lib/WebSocketConnection.js:793:14)
    at WebSocketConnection.sendUTF (/media/bintex/ubuntu/yolo/test/lab-opendatacam/node_modules/websocket/lib/WebSocketConnection.js:733:10)
    at Timeout.sendDetection [as _onTimeout] (/media/bintex/ubuntu/yolo/test/lab-opendatacam/server/processes/YOLO.js:102:28)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```

**Comment by florianporada** [comment] 2019-01-10 08:37
Hi @syedmustafa54, which weight files are you using?

**Comment by syedmustafa54** [comment] 2019-01-10 08:59
hi @florianporada  I am using yolo-voc.weights

**Comment by syedmustafa54** [comment] 2019-01-10 09:05
Sorry Forgot to mention I am using ubuntu 16.04 and 8gb ram 1080ti Nvidia graphics

**Comment by tdurand** [comment] 2019-01-10 10:39
I think it is due to the Websocket package which has a bug with recent node version: https://github.com/ethereum/web3.js/issues/1613 

Can you give us your node version ? Type "node --version" in the command line

Will try to reproduce and fix today

**Comment by syedmustafa54** [comment] 2019-01-10 10:53
Node - v10.15.0
npm -v
here is the log file
```0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@6.4.1
3 info using node@v10.15.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle open-data-cam@0.2.2~predev: open-data-cam@0.2.2
6 info lifecycle open-data-cam@0.2.2~dev: open-data-cam@0.2.2
7 verbose lifecycle open-data-cam@0.2.2~dev: unsafe-perm in lifecycle true
8 verbose lifecycle open-data-cam@0.2.2~dev: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/media/bintex/ubuntu/yolo/test/lab-opendatacam/lab-open-data-cam/node_modules/.bin:/usr/local/cuda-9.2/bin:/home/bintex/anaconda3/bin:/home/bintex/anaconda3/bin:/home/bintex/anaconda3/bin:/home/bintex/anaconda3/bin:/home/bintex/bin:/home/bintex/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle open-data-cam@0.2.2~dev: CWD: /media/bintex/ubuntu/yolo/test/lab-opendatacam/lab-open-data-cam
10 silly lifecycle open-data-cam@0.2.2~dev: Args: [ '-c', 'node server.js' ]
11 silly lifecycle open-data-cam@0.2.2~dev: Returned: code: 1  signal: null
12 info lifecycle open-data-cam@0.2.2~dev: Failed to exec dev script
13 verbose stack Error: open-data-cam@0.2.2 dev: `node server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid open-data-cam@0.2.2
15 verbose cwd /media/bintex/ubuntu/yolo/test/lab-opendatacam/lab-open-data-cam
16 verbose Linux 4.15.0-43-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
18 verbose node v10.15.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error open-data-cam@0.2.2 dev: `node server.js`
22 error Exit status 1
23 error Failed at the open-data-cam@0.2.2 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]```

**Comment by tdurand** [comment] 2019-01-10 11:48
Confirmed it was because of node v10, if you use node lower than v10 it should work. I'll fix the bug for nodev10

**Comment by tdurand** [comment] 2019-01-10 13:35
Fixed on v0.2.3 https://github.com/moovel/lab-opendatacam/releases/tag/v0.2.3 

Do a git pull + npm install + npm run build and it should fix the issue, otherwise please re-open

**Comment by syedmustafa54** [comment] 2019-01-10 14:23
Don't know why its running without giving PATH_TO_YOLO_DARKNET
even conting objects any help 
i tryed to give my path and webcam 
and than npm run build 
What I did  
`git pull https://github.com/moovel/lab-opendatacam.git`
``` git pull https://github.com/moovel/lab-opendatacam.git
From https://github.com/moovel/lab-opendatacam
 * branch            HEAD       -> FETCH_HEAD
Updating bc444ef..2007f19
Fast-forward
 README.md                 | 10 ++++++++--
 config.json               |  2 +-
 package-lock.json         | 22 ++++++++++++++--------
 package.json              |  4 ++--
 server/counter/Counter.js |  2 +-
 yarn.lock                 | 27 ++++++++++++++++-----------
 6 files changed, 42 insertions(+), 25 deletions(-)
```
```
this is your path but its is stll running 
"PATH_TO_YOLO_DARKNET" : "/home/nvidia/darknet-net",
  "VALID_CLASSES": ["*"]
```
![image](https://user-images.githubusercontent.com/24798263/50974370-17d56880-1511-11e9-96f6-78c8488f61ef.png)

**Comment by syedmustafa54** [comment] 2019-01-10 14:54
@tdurand  thanks, it's running but I cannot see real-time detection but its counting and drawing graph 
but I have 1080ti GPU and it's using only 1gb of it how can I use it 100% is there any config to do that

**Comment by tdurand** [comment] 2019-01-10 15:00
Great !

Unfortunately we do not have the real-time detection preview implemented yet because this was aimed to be run on a Jetson TX2 which didn't support it.. (perfs were really bad)

But good news is that we are working on a new update for Jetson Xavier: https://github.com/moovel/lab-opendatacam/issues/45 , and we will probably at the option of a live preview along with new features in it. So follow along the activity on this repo 😉

I'm curious, I guess the 1080ti runs open data cam at 30 FPS ?

**Closed** 2019-01-10 15:08 UTC

**Comment by syedmustafa54** [comment] 2019-01-11 07:47
yes I am getting 30 fps but is there any way to see output like shown in the [video](https://vimeo.com/260744286) on 49 sec I need to show output

**Comment by tdurand** [comment] 2019-01-11 10:15
For now it's not possible, we had an early prototype working with this but as it wasn't running smoothly on the Jetson TX2 we disabled it... But good news is we are working on a new update with this live preview 🎉 , watch this repo it should be out soon !
